### ISSUE TITLE
PermissionPlugin.Check() never returns when permission is not granted ?

### ISSUE THREAD

**Issue by Vinnythetrue** [hiyorin/PermissionPlugin-for-Unity#1]
Hi,
In my project I need both camera and location permissions for some features. So I'm using this plugin in order to do so :

`
    private IEnumerator ASyncCheckPermission()
    {
        switch (_permissionType)
        {
            case Permission.Camera:
                yield return PermissionPlugin.Check(PermissionPlugin.Permission.Camera, result => bPermissionGranted = result);
                break;

            case Permission.Location:
                yield return PermissionPlugin.Check(PermissionPlugin.Permission.Location, result => bPermissionGranted = result);
                break;
        }

        yield return OnPermission(bPermissionGranted);
    }`

According to my logs, OnPermission(bool) never actually gets called if the user didn't give the asked permission.... I can see dialogs asking me for permission on my Android phone though.
If permissions are given, my function gets called and I can see the logs I put in.

Is this an issue with recent Android versions ? Should I expect same situation on iOS ?

BR,
Vinny

**Comment by hiyorin** [comment]
Sorry, It works on my device...
device: Galaxy s6 edge
version: 7.0

Are you using com.hiyorin.permission.CustomUnityPlayerActivity?
CustomUnityPlayerActivity is handling onRequestPermissionsResult.

**Comment by hiyorin** [comment]
The description about MainActivity was missing.
Readme has been updated.
